### ISSUE TITLE
Sharing the test code visual the result

### ISSUE THREAD

**Issue by gaowq2017** [lizhaoliu-Lec/DAS#1]
Hi, thanks for sharing the code
    Could you sharing the test code that visualising the result image, e.g hotmap or others
Thank you！

**Comment by lizhaoliu-Lec** [comment]
The code for visualizing the frequency recorder matrix (_e.g.,_ heatmap ) is in [visFRM.](https://github.com/lizhaoliu-Lec/DAS/tree/master/others/visFRMClean)
What are the others mean? There are many figs in the paper and we may not have time to clean up and organize the related code. Please be more specific.
